### ISSUE TITLE
saveForm and deleteForm throw an error when no button defined.

### ISSUE THREAD

**Issue by bybrunobarros** [cferdinandi/form-saver#23]
When saveForm or deleteForm are called without a button as their first argument getDataOptions throws an error. An empty object {} is used as a default value instead of its string counterpart "{}".
Json.parse in getDataOptions waits for a string.

**Comment by cferdinandi** [comment]
@bybrunobarros Good catch! Will fix asap...

**Comment by cferdinandi** [comment]
Fixed with https://github.com/cferdinandi/form-saver/pull/24. Thanks again!

**Comment by bybrunobarros** [comment]
Thank you for this nice little script.
