### ISSUE TITLE
Just a lil thanks!

### ISSUE THREAD

**Issue by CanRau** [cferdinandi/form-saver#25]
Thank you for this great little plugin!!

Couple of days ago I was to lazy to code a little form saver for a project. Just stumbled across your great plugin, installed and ready!

Luckily you implemented the api for custom stuff :)

Thanks a lot!

**Comment by cferdinandi** [comment]
Delighted to hear this! And I'm glad the API came in handy. I end up using it myself on most of my projects. Cheers!
