### ISSUE TITLE
Select value change does not trigger change event

### ISSUE THREAD

**Issue by set-webmaster** [cferdinandi/form-saver#37]
When using the `loadForm` function programmatically and one of the fields is a `select` element, the value is effectively updated, but the change event is not triggered, which can cause problems. 

In my case, I use Select2 to enhance select boxes, and it seems to rely on the change event to update accordingly to the newly selected value. 

It would be nice if something like that could be added:
```
<selectElement>.dispatchEvent(new Event("change"));
```
after the select value has been updated.

If you have concerns about it, I would like to know them, otherwise it would be a good addition IMO :)

**Comment by cferdinandi** [comment]
I'm not sure I fully understand what's going on here. Is select2 changing the markup in a weird way? Reduced test case please.

**Comment by set-webmaster** [comment]
Here's a small snippet of what's generated by Select2 after being initialized
```
<div class="form-group">
    <select class="form-control js-select2-init" id="targetValue" name="targetValue">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
    </select>
    <span class="select2 select2-container select2-container--bootstrap" dir="ltr" style="width: 100%;">
        <span class="selection">
            <span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-targetValue-container">
                <span class="select2-selection__rendered" id="select2-targetValue-container" title="1">1</span>
                <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span>
            </span>
        </span>
        <span class="dropdown-wrapper" aria-hidden="true"></span>
    </span>
</div>
```

If I use form-saver to save/load the value of this select element, the following happens:
1. The save works as expected 
2. When loading, the value of the Select element is updated (for example from 1 to 3)
3. The Select2 text displayed within the span that is generated from Select2 still displays 1 instead of the new value of 3, it hasn't been notified of the `select` value change, and hence did not update accordingly.

I proposed a PR that would fix this issue by triggering a `change` event whenever a `select-one` field is updated.

**Comment by cferdinandi** [comment]
This feels like an issue with your other plugin/script using nonstandard elements in the UI.

Could you achieve the same result by loading that plugin _after_ formSaver loads saved data back into the UI?

**Comment by set-webmaster** [comment]
I could effectively do that, but that doesn't really fix the issue, it only works around it. 

But, in my opinion, there's not only Select2 that could rely on the Select element change event to be triggered, it also does not really add any complexity to the codebase to add the event trigger does it?

**Comment by cferdinandi** [comment]
My hesitancy here is that I don't think of what the script does as updating a field, but rather setting its default value on page load.

It's analogous to adding the `selected` attribute to an `option` in the server-rendered markup.

With that mental model in mind, what you're asking for in the code is, in my opinion, more of a workaround than what I'm actually suggesting. I believe you should treat the script as a way to set the default markup on page load, and therefore, it should be loaded/run _before_ Select2.

**Comment by set-webmaster** [comment]
I understand your reasoning and I totally respect it. I guess we will just have to agree to disagree here hehe :)

It's a difference between `updating` the field and make sure other parts of the app are notified, vs ensuring the script loading is in the correct order (which is not my preferred approach, but it's yours and I respect it)

I will then close the issue and simply implement the change in my local version. 

Thanks for your time and consideration and have a great day!
